flowchart LR
    %% Define nodes and subgraphs
    subgraph TS["Tanium Server All-In-One"]
        subgraph TS_CGN["Cologne, DE"]
            TS_CGN_1["cgnpwtan01.jomax.paholdings.com"]
        end
    end
    
    %% Define nodes not part of a subgraph
    Title("Tanium Production EMEA (Works Council)"):::StyleGoDaddyProdEMEA
    TaniumClient["Tanium Client"]
    TaniumConsole["Tanium Console<br/>https://wc-tanium.int.gdcorp.tools"]
    RDPBastion["RDP Bastion Host<br/>cgnpwbastion01.gde.systems"]
    RDPClient["RDP Client"]

    %% Define relationships
    TaniumClient -.->|"TCP/17472,17475"| TS_CGN
    TaniumConsole -->|"TCP/443"| TS_CGN
    RDPClient -->|"TCP/UDP/3389"| RDPBastion -->|"TCP/UDP/3389"| TS_CGN

    %% Add hyperlinks
    click TaniumConsole "https://wc-tanium.int.gdcorp.tools" "Tanium Console (VPN Required)"

    %% Define styles
    classDef StyleGoDaddyProd fill:#E22726,color:#000000,stroke:#FFFFFF,stroke-width:1px;
    classDef StyleGoDaddyProdEMEA fill:#FED317,color:#2F1C4C,stroke:#FADCD9,stroke-width:1px;
    classDef StyleGoDaddyDev fill:#00782E,color:#D8EFEF,stroke:#FFEEA9,stroke-width:1px;
    
    %% Assign styles
    %%class Title StyleGoDaddyProdEMEA;