flowchart LR
    %% Define nodes and subgraphs
    subgraph TS["Tanium Server"]
        subgraph TS_A2["Ashburn, VA, USA"]
            TS_A2_1["a2pwtaniumhub01.dc1.corp.gd"]
            TS_A2_2["a2pwtaniumhub02.dc1.corp.gd"]
            TS_A2_1 <-->|"TCP/17472"| TS_A2_2
        end
    end
    subgraph MS["Tanium Module Server"]
        subgraph MS_P3["Phoenix, AZ, USA"]
            MS_P3_1["p3pwtaniummod01"]
        end
    end
    subgraph ZS["Tanium Zone Server"]
        subgraph ZS_A2["Ashburn, VA, USA"]
            ZS_A2_1["a2pwtaniumzon01.dc1.corp.gd<br/>Internal & External"]
            ZS_A2_2["a2pwtaniumzon02.cloud.iad2.gdg<br/>Internal Only"]
        end
        subgraph ZS_P3["Phoenix, AZ, USA"]
            ZS_P3_1["p3pwtaniumzon01.dc1.corp.gd<br/>Internal & External"]
            ZS_P3_2["p3pwtaniumzon02.cloud.phx3.gdg<br/>Internal Only"]
        end
        subgraph ZS_SG2["Singapore, SG"]
            ZS_SG2_1["sg2pwtaniumzs01.cloud.sin2.gdg<br/>Internal Only"]
        end
        subgraph ZS_CGN["Cologne, DE"]
            ZS_CGN_1["cgn-tan-zon001.jomax.paholdings.com<br/>Internal & External"]
        end
    end
    subgraph ZH["Tanium Zone Server Hub"]
        subgraph ZH_A2["Ashburn, VA, USA"]
            ZH_A2_1["p3pwtaniumhub03.cloud.phx3.gdg"]
        end
    end
    subgraph SQL["SQL Server"]
        subgraph SQL_A2["Ashburn, VA, USA"]
            SQL_A2_3[("A2PWTANSOCSQL03")]
            SQL_A2_4[("A2PWTANSOCSQL04")]
            SQL_A2_3 <--> SQL_A2_4
        end
    end
    
    %% Define nodes not part of a subgraph
    %%Title("Tanium Production"):::StyleGoDaddyProd
    TaniumClient["Tanium Client"]
    TaniumConsole["Tanium Console<br/>https://tanium.int.gdcorp.tools"]

    %% Define relationships
    TS_A2 -->|"TCP/17477"| MS_P3
    MS_P3 -->|"TCP/443"| TS_A2
    TS_A2 -->|"TCP/1433<br/>to<br/>A2PWTANSOCSQL03"| SQL_A2_3
    TS_A2 --> ZH_A2
    TS_A2 -->|"TCP/17472"| ZS_A2
    TS_A2 -->|"TCP/17472"| ZS_P3
    TS_A2 -->|"TCP/17472"| ZS_SG2
    ZH_A2 --> ZS_CGN
    TaniumClient -.->|"TCP/17472<br/>Unused"| TS_A2
    TaniumClient -.->|"TCP/17475<br/>Unused"| MS_P3
    TaniumClient -.->|"TCP/17472,17500<br/>Direct Connect Enabled<br/>EMEA Computers Only"| ZS_CGN
    TaniumClient -.->|"TCP/17472,17500<br/>Direct Connect Enabled"| ZS_A2_1
    TaniumClient -.->|"TCP/17472"| ZS_A2_2
    TaniumClient -.->|"TCP/17472,17500<br/>Direct Connect Enabled"| ZS_P3_1
    TaniumClient -.->|"TCP/17472"| ZS_P3_2
    TaniumClient -.->|"TCP/17472"| ZS_SG2
    TaniumConsole -->|"TCP/443"| TS_A2
    
    %% Add hyperlinks
    click TaniumConsole "https://tanium.int.gdcorp.tools" "Tanium Console (VPN Required)"

    %% Define styles
    classDef StyleGoDaddyProd fill:#E22726,color:#000000,stroke:#FFFFFF,stroke-width:1px;
    classDef StyleGoDaddyProdEMEA fill:#FED317,color:#2F1C4C,stroke:#FADCD9,stroke-width:1px;
    classDef StyleGoDaddyDev fill:#00782E,color:#D8EFEF,stroke:#FFEEA9,stroke-width:1px;

    %% Assign styles
    %%class Title StyleGoDaddyProd;