graph LR
    subgraph TS["Tanium Server (HA)"]
        subgraph MS_A2["Ashburn, VA, USA"]
            TS_A2_1["A2PWTANIUMHUB01"]
            TS_A2_2["A2PWTANIUMHUB02"]
            TS_A2_1 <-->|"TCP/17472"| TS_A2_2
            TS_A2_2 <-->|"TCP/17472"| TS_A2_1
        end
    end
    subgraph MS["Tanium Module Server"]
        subgraph MS_P3["Phoenix, AZ, USA"]
            MS_P3_1["P3PWTANIUMMOD01"]
        end
    end
    subgraph ZS["Tanium Zone Server"]
        subgraph ZS_A2["Ashburn, VA, USA"]
            ZS_A2_1["A2PWTANIUMZON01"]
            ZS_A2_2["A2PWTANIUMZON02"]
        end
        subgraph ZS_P3["Phoenix, AZ, USA"]
            ZS_P3_1["P3PWTANIUMZON01"]
            ZS_P3_2["P3PWTANIUMZON02"]
        end
        subgraph ZS_CGN["Cologne, DE"]
            ZS_CGN_1["CGN-TAN-ZON001<br>(EMEA Systems Only)"]
        end
        subgraph ZS_SG2["Singapore, SG"]
            ZS_SG2_1["SG2PWTANIUMZS01"]
        end
    end
    subgraph ZH["Tanium Zone Server Hub"]
        subgraph ZH_A2["Ashburn, VA, USA"]
            ZH_A2_1["A2PWTANIUMHUB03"]
        end
    end
    subgraph SQL["SQL Server"]
        subgraph SQL_A2["Ashburn, VA, USA"]
            SQL_A2_3["A2PWTANSOCSQL03"]
            SQL_A2_4["A2PWTANSOCSQL04"]
            SQL_A2_3 --> SQL_A2_4
            SQL_A2_4 --> SQL_A2_3
        end
    end
    External["External Clients"]
    Internal["Internal Clients"]
    Console["Tanium Console"]

    TS -->|"TCP/17477"| MS
    TS -->|"TCP/1433,5432"| SQL
    TS --> ZH
    TS -->|"TCP/17472"| ZS
    Console -->|"TCP/443"| TS
    Internal -->|"TCP/17472<br>Unused"| TS
    MS -->|"TCP/443"| TS
    ZH --> ZS_CGN
    External -->|"TCP/17472,17500"| ZS
